var gtgpConfig = {
  baseSheetName: 'Base_Principal',
  agentSheetName: 'TB_Agente',
  joinKey: 'matricula',
  nameKey: 'nome',
  xlsxMimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xlsxFilePrefix: 'gtgp-pessoas-',
  xlsxSheetName: 'Pessoas',
  numericFieldKeys: ['idade', 'nota20261', 'nota20262', 'ultimanota'],
  fieldLabels: {
    dataefetivo: 'Data efetiva',
    matricula: 'Matrícula',
    nome: 'Nome',
    descricaocargo: 'Cargo',
    idade: 'Idade',
    sexo: 'Sexo',
    programavigente: 'Programa vigente',
    statustrainee: 'Status trainee',
    enquadre: 'Enquadre',
    dataadmissao: 'Data de admissão',
    geracaogt: 'Geração GT',
    geracaogp: 'Geração GP',
    tempocasa: 'Tempo de casa',
    descricaoceo1: 'Estrutura · nível 1',
    descricaoceo2: 'Estrutura · nível 2',
    descricaoceo3: 'Estrutura · nível 3',
    descricaoceo4: 'Estrutura · nível 4',
    descricaoceo5: 'Estrutura · nível 5',
    descricaoceo6: 'Estrutura · nível 6',
    descricaoceo7: 'Estrutura · nível 7',
    centrocusto: 'Centro de custo',
    descricaonivel1: 'Descrição do nível 1',
    nivel2: 'Nível 2',
    localidade: 'Localidade',
    curso: 'Curso',
    instituicao: 'Instituição',
    observacao: 'Observação',
    vagamapeada: 'Vaga mapeada',
    industrialstaff: 'Industrial / Staff',
    rotacao: 'Rotação',
    exestagiario: 'Ex-estagiário',
    areafim: 'Área final',
    nota20261: 'Nota 2026.1',
    potencial20261: 'Potencial 2026.1',
    etapa20262: 'Etapa 2026.2',
    nota20262: 'Nota 2026.2',
    potencial20262: 'Potencial 2026.2',
    historicoavaliacoes: 'Histórico de avaliações',
    ultimocicloavaliacao: 'Último ciclo avaliado',
    ultimanota: 'Última nota registrada',
    ultimopotencial: 'Último potencial registrado'
  }
};
