var gtgpConfig = {
  legacyBaseSheetName: 'Base_Principal',
  legacyAgentSheetName: 'TB_Agente',
  joinKey: 'matricula',
  nameKey: 'nome',
  xlsxMimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xlsxFilePrefix: 'gtgp-pessoas-',
  xlsxSheetName: 'Pessoas',
  numericFieldKeys: ['idade', 'nota20261', 'nota20262'],
  fieldLabels: {
    dataefetivo: 'Data efetiva',
    matricula: 'Matrícula',
    nome: 'Nome',
    descricaocargo: 'Cargo',
    idade: 'Idade',
    sexo: 'Sexo',
    programavigente: 'Programa vigente',
    statustrainee: 'Status trainee',
    enquadre: 'Enquadre',
    dataadmissao: 'Data de admissão',
    geracaogt: 'Geração GT',
    geracaogp: 'Geração GP',
    tempocasa: 'Tempo de casa',
    comentarios: 'Comentários',
    areafimceo1: 'Área-fim · CEO1',
    areafimceo2: 'Área-fim · CEO2',
    areafimceo3: 'Área-fim · CEO3',
    areafimceo4: 'Área-fim · CEO4',
    areafimceo5: 'Área-fim · CEO5',
    ceo3atual: 'CEO3 atual',
    ceo4atual: 'CEO4 atual',
    ceo5atual: 'CEO5 atual',
    detalhevaga: 'Detalhe da vaga',
    rotacao1: 'Rotação 1',
    rotacao2: 'Rotação 2',
    rotacao3: 'Rotação 3',
    rotacao4: 'Rotação 4',
    previsaodeformatura: 'Previsão de formatura',
    centrocusto: 'Centro de custo',
    descricaonivel1: 'Descrição do nível 1',
    nivel2: 'Nível 2',
    localidade: 'Localidade',
    curso: 'Curso',
    instituicao: 'Instituição',
    vagamapeada: 'Vaga mapeada',
    industrialstaff: 'Industrial / Staff',
    nota20261: 'Nota 2026.1',
    potencial20261: 'Potencial 2026.1',
    etapa20262: 'Etapa 2026.2',
    nota20262: 'Nota 2026.2',
    potencial20262: 'Potencial 2026.2'
  }
};
